version: 2

jobs:
  build:
  
    docker:
      - image: eglint/pjass

    steps:
      - run: git clone -b "wc3-pre-1.29" "https://github.com/eGlint/Warcraft-III-Noise-Library"

      - run:
          name: Moving JASS files to root directory
          command: mv JASS/test/*.j .; mv JASS/*.j .;

      - run:
          name: Test
          command: pjass /root/common.j /root/blizzard.j noise-pjass-defined-udg.j Noise.j OctavePerlin.j
