version: 2

jobs:
  build:

    docker:
      - image: eglint/pjass

    steps:
      - checkout

      - run:
          name: Check directory
          command: ls

      - run:
          name: Moving JASS files to root directory
          command: mv JASS/test/*.j . & mv JASS/*.j .

      - run:
          name: Test Noise.j
          command: pjass /root/common.j /root/blizzard.j noise-pjass-defined-udg.j Noise.j

      - run:
          name: Test OctavePerlin
          command: pjass /root/common.j /root/blizzard.j OctavePerlin.j
