name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: eglint/pjass

    steps:
      - uses: actions/checkout@V4

      - name: mv JASS/test/*.j . & mv JASS/*.j .
        run: Moving JASS files to root directory

      - name: Test
        run: pjass /root/common.j /root/blizzard.j noise-pjass-defined-udg.j Noise.j OctavePerlin.j
